/**
 *        _            ____                     _ _             ____
 *  _ __ | |__  _ __  / ___|_   _  __ _ _ __ __| (_) __ _ _ __ |___ \
 * | '_ \| '_ \| '_ \| |  _| | | |/ _` | '__/ _` | |/ _` | '_ \  __) |
 * | |_) | | | | |_) | |_| | |_| | (_| | | | (_| | | (_| | | | |/ __/
 * | .__/|_| |_| .__/ \____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_|_____|
 * |_|         |_| phpGuardian CLI
 *
 *
 * PHPGUARDIAN2
 *
 * CODE NAME:      phoenix
 * ENGINE VERSION: 4.0
 * MODULE VERSION: 1.0
 *
 * URL:            http://www.phpguardian.org
 * E-MAIL:         info@phpguardian.org
 *
 * COPYRIGHT:      2006-2011 Fabio Cicerchia
 * LICENSE:        GNU GPL 3+
 *                 This program is free software: you can redistribute it and/or
 *                 modify it under the terms of the GNU General Public License
 *                 as published by the Free Software Foundation, either version
 *                 3 of the License, or (at your option) any later version.
 *
 *                 This program is distributed in the hope that it will be
 *                 useful, but WITHOUT ANY WARRANTY; without even the implied
 *                 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *                 PURPOSE. See the GNU General Public License for more details.
 *
 *                 You should have received a copy of the GNU General Public
 *                 Licensealong with this program. If not, see
 *                 <http://www.gnu.org/licenses/>.
 *
 * $Id: $
 **/

#include "../decoder.c"

/*
char *pg_code_decrypt(char *data) {
    int ld = (int)strlen(data), lk = (int)strlen(PG_S_KEY_HASH);

    // Increase file counter
    total_files++;

    // Check content size
    if (ld == 0) {
        pg_message("WARNING: Skipped because the file content is empty.", false);
        return NULL;
    }

    // Check key size
    if (lk == 0) {
        pg_message("ERROR: Skipped because the private key is empty.", false);
        return NULL;
    }

    // Check if is a phpguardian file
    int start = strpos(data, "phpg_exec('", 0);
    int end = strpos(data, "')", start);
    if (start == -1 || end == -1) {
        pg_message("ERROR: Skipped because isn't a phpguardian file.", false);
        return "";
    }
    start += 11;

    // Get the encoded data
    char *tmpdata = (char *)malloc(((end - start) + 1) * sizeof(char));
    strncpy(tmpdata, data + start, end - start);
    tmpdata[end - start] = '\0';
    ld = end - start;

    if (tmpdata[ld] == '\0' && ((ld % 2) != 0)) {
        ld--;
    }
    tmpdata[ld] = '\0';

    // Print a message
    pg_message("Decoding %d bytes...", true, ld);

    // Decrypt the data
    char *crdata = pg_cycle_decrypt(tmpdata, lk, ld);
    free(tmpdata);

    // Increase the total generated bytes
    total_generated_bytes += strlen(crdata);

    // Print a message
    pg_message("Restored %d bytes.", true, strlen(crdata));

    return crdata;
}
*/

void test_decoder_pg_code_decrypt_success1(void) {
   CU_ASSERT(true);
}

CU_pSuite decoder_pg_code_decrypt_create_suite(CU_pSuite pSuite) {
    /* add the tests to the suite */
    if (
        (NULL == CU_add_test(pSuite, "test_decoder_pg_code_decrypt_success1", test_decoder_pg_code_decrypt_success1))
       ) {
        return NULL;
    }

    return pSuite;
}