/**
 *        _            ____                     _ _             ____
 *  _ __ | |__  _ __  / ___|_   _  __ _ _ __ __| (_) __ _ _ __ |___ \
 * | '_ \| '_ \| '_ \| |  _| | | |/ _` | '__/ _` | |/ _` | '_ \  __) |
 * | |_) | | | | |_) | |_| | |_| | (_| | | | (_| | | (_| | | | |/ __/
 * | .__/|_| |_| .__/ \____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_|_____|
 * |_|         |_| phpGuardian CLI
 *
 *
 * PHPGUARDIAN2
 *
 * CODE NAME:      phoenix
 * ENGINE VERSION: 4.0
 * MODULE VERSION: 1.0
 *
 * URL:            http://www.phpguardian.org
 * E-MAIL:         info@phpguardian.org
 *
 * COPYRIGHT:      2006-2011 Fabio Cicerchia
 * LICENSE:        GNU GPL 3+
 *                 This program is free software: you can redistribute it and/or
 *                 modify it under the terms of the GNU General Public License
 *                 as published by the Free Software Foundation, either version
 *                 3 of the License, or (at your option) any later version.
 *
 *                 This program is distributed in the hope that it will be
 *                 useful, but WITHOUT ANY WARRANTY; without even the implied
 *                 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *                 PURPOSE. See the GNU General Public License for more details.
 *
 *                 You should have received a copy of the GNU General Public
 *                 Licensealong with this program. If not, see
 *                 <http://www.gnu.org/licenses/>.
 *
 * $Id: $
 **/

#include "../main.c"

/*
static void report(int start_time) {
    int i;
    printf("-------------------------\n");
    printf(_("Total time: %lds"), (time(NULL) - start_time));
    printf("\n\n");
    printf(_("Total files processed: %d"), total_files);
    printf("\n");
    printf(_("Total files skipped: %d"), count_skipped);
    printf("\n");
    if (count_skipped > 0) {
        char *skipped = _("Skipped files:");
        printf("\t%s\n", skipped);
        free(skipped);
        for(i = 0; i < count_skipped; i++) {
            printf("\t%s\n", skipped_files[i]);
        }
    }
    printf(_("Total bytes processed: %ld"), total_orig_bytes);
    printf("\n");
    if (strcmp(PG_S_ACTION, "ENCODE") == 0) {
        printf(_("Total converted bytes: %ld"), total_converted_bytes);
        printf("\n");
    }
    printf(_("Total generated bytes: %ld"), total_generated_bytes);
    printf("\n\n");
    if (strcmp(PG_S_ACTION, "ENCODE") == 0) {
        printf(_("Total size increasing: %ldb"), (total_generated_bytes-total_orig_bytes));
        printf("\n");
        printf(_("Total size increasing: %2.2f%%"), (float)((100.0 / total_orig_bytes) * total_generated_bytes));
        printf("\n");
    } else if (strcmp(PG_S_ACTION, "DECODE") == 0) {
        printf(_("Total size decreasing: %ldb"), (total_orig_bytes-total_generated_bytes));
        printf("\n");
        printf(_("Total size decreasing: %2.2f%%"), (float)((100.0 / total_orig_bytes) * total_generated_bytes));
        printf("\n");
    }
}
*/

void test_main_report_success1(void) {
   CU_ASSERT(true);
}

CU_pSuite main_report_create_suite(CU_pSuite pSuite) {
    /* add the tests to the suite */
    if (
        (NULL == CU_add_test(pSuite, "test_main_report_success1", test_main_report_success1))
       ) {
        return NULL;
    }

    return pSuite;
}