/**
 *        _            ____                     _ _             ____
 *  _ __ | |__  _ __  / ___|_   _  __ _ _ __ __| (_) __ _ _ __ |___ \
 * | '_ \| '_ \| '_ \| |  _| | | |/ _` | '__/ _` | |/ _` | '_ \  __) |
 * | |_) | | | | |_) | |_| | |_| | (_| | | | (_| | | (_| | | | |/ __/
 * | .__/|_| |_| .__/ \____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_|_____|
 * |_|         |_| phpGuardian CLI
 *
 *
 * PHPGUARDIAN2
 *
 * CODE NAME:      phoenix
 * ENGINE VERSION: 4.0
 * MODULE VERSION: 1.0
 *
 * URL:            http://www.phpguardian.org
 * E-MAIL:         info@phpguardian.org
 *
 * COPYRIGHT:      2006-2011 Fabio Cicerchia
 * LICENSE:        GNU GPL 3+
 *                 This program is free software: you can redistribute it and/or
 *                 modify it under the terms of the GNU General Public License
 *                 as published by the Free Software Foundation, either version
 *                 3 of the License, or (at your option) any later version.
 *
 *                 This program is distributed in the hope that it will be
 *                 useful, but WITHOUT ANY WARRANTY; without even the implied
 *                 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *                 PURPOSE. See the GNU General Public License for more details.
 *
 *                 You should have received a copy of the GNU General Public
 *                 Licensealong with this program. If not, see
 *                 <http://www.gnu.org/licenses/>.
 *
 * $Id: $
 **/

#include "../encoder.c"

/*
char *pg_code_crypt(char *data) {
    int i, ld = (int)strlen(data), lk = (int)strlen(PG_S_KEY_HASH);

    // Increase file counter
    total_files++;

    // Check content size
    if (ld == 0) {
        pg_message("WARNING: Skipped because the file content is empty.", false);
        return "";
    }

    // Check key size
    if (lk == 0) {
        pg_message("ERROR: Skipped because the private key is empty.", false);
        return "";
    }

    // Print a message
    pg_message("Encoding %d bytes...", true, ld);

    char *crdata = (char *)malloc(((2 * ld) + 1) * sizeof(char));
    memset(crdata, 0, sizeof(crdata));

    // Encode the data
    for(i = 0; i < ld; i++) {
        strcat(crdata, encode_char(data[i], PG_S_KEY_HASH[i % lk]));
    }
    crdata[2 * ld] = '\0';

    // Increase the total generated bytes
    total_generated_bytes += strlen(crdata);

    // Print a message
    pg_message("Generated %d bytes.", true, strlen(crdata));

    return crdata;
}
*/

void test_encoder_pg_code_crypt_success1(void) {
   CU_ASSERT(true);
}

CU_pSuite encoder_pg_code_crypt_create_suite(CU_pSuite pSuite) {
    /* add the tests to the suite */
    if (
        (NULL == CU_add_test(pSuite, "test_encoder_pg_code_crypt_success1", test_encoder_pg_code_crypt_success1))
       ) {
        return NULL;
    }

    return pSuite;
}